apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-product-catalog
  annotations:
    github.com/project-slug: dev-future-tech/online-product-catalog
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: production
  owner: user:anthonyikeda
  system: online-retail
